# Generated by Django 3.0.8 on 2020-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='address_line2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='pune', max_length=40),
        ),
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default='410507'),
        ),
    ]
